const r=require('express').Router();
const {protect,authorize}=require('../middleware/auth');
const {loadProject,requireProjectPermission}=require('../middleware/projectAccess');
const c=require('../controllers/consultingOperationsController');
r.use(protect);
r.get('/proposals',c.listProposals);
r.post('/proposals',authorize('admin','super_admin','project_manager'),c.createProposal);
r.put('/proposals/:id/decision',c.decideProposal);
r.put('/proposals/:id',authorize('admin','super_admin','project_manager'),c.updateProposal);
r.put('/proposals/:id/status',authorize('admin','super_admin','project_manager'),c.transitionProposal);
r.post('/proposals/:id/send',authorize('admin','super_admin','project_manager'),c.sendProposal);
r.get('/projects',c.listProjects);
r.get('/projects/:id',loadProject,c.getProject);
r.put('/projects/:id',loadProject,requireProjectPermission('manageProject'),c.updateProject);
r.post('/projects/:projectId/milestones',loadProject,requireProjectPermission('manageTasks'),c.createMilestone);
r.post('/projects/:projectId/tasks',loadProject,requireProjectPermission('manageTasks'),c.createTask);
r.put('/projects/:projectId/tasks/:taskId',loadProject,requireProjectPermission('manageTasks'),c.updateTask);
r.post('/projects/:projectId/deliverables',loadProject,requireProjectPermission('uploadFiles'),c.createDeliverable);
r.put('/projects/:projectId/deliverables/:deliverableId/review',loadProject,requireProjectPermission('reviewDeliverables'),c.reviewDeliverable);
r.post('/projects/:projectId/contracts',loadProject,requireProjectPermission('manageContracts'),c.createContract);
r.post('/projects/:projectId/contracts/:contractId/sign',loadProject,c.signContract);
r.post('/projects/:projectId/invoices',loadProject,requireProjectPermission('createInvoices'),c.createInvoice);
r.put('/projects/:projectId/invoices/:invoiceId/status',loadProject,requireProjectPermission('manageInvoices'),c.updateInvoiceStatus);
module.exports=r;
