const r=require('express').Router();
const {protect,authorize}=require('../middleware/auth');
const {loadProject,requireProjectPermission}=require('../middleware/projectAccess');
const c=require('../controllers/consultingOperationsController');
r.use(protect);
r.get('/proposals',c.listProposals);
r.post('/proposals',authorize('admin','super_admin','project_manager'),c.createProposal);
r.put('/proposals/:id/decision',c.decideProposal);
r.get('/projects',c.listProjects);
r.get('/projects/:id',loadProject,c.getProject);
r.post('/projects/:projectId/milestones',loadProject,requireProjectPermission('manageTasks'),c.createMilestone);
r.post('/projects/:projectId/tasks',loadProject,requireProjectPermission('manageTasks'),c.createTask);
r.put('/tasks/:id',c.updateTask);
r.post('/projects/:projectId/deliverables',loadProject,requireProjectPermission('uploadFiles'),c.createDeliverable);
r.put('/deliverables/:id/review',authorize('admin','super_admin','project_manager','technical_reviewer'),c.reviewDeliverable);
r.post('/projects/:projectId/contracts',loadProject,authorize('admin','super_admin','project_manager'),c.createContract);
r.post('/projects/:projectId/invoices',loadProject,authorize('admin','super_admin','finance'),c.createInvoice);
r.put('/invoices/:id/status',authorize('admin','super_admin','finance'),c.updateInvoiceStatus);
module.exports=r;
