const r=require('express').Router();
const multer=require('multer');
const rateLimit=require('express-rate-limit');
const {protect,requireVerifiedEmail}=require('../middleware/auth');
const {loadProject,requireProjectPermission}=require('../middleware/projectAccess');
const c=require('../controllers/projectDocumentController');
const allow=['application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','image/png','image/jpeg'];
const up=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:1},fileFilter:(q,f,cb)=>cb(allow.includes(f.mimetype)?null:new Error('File type not allowed'),allow.includes(f.mimetype))});
const uploadLimiter=rateLimit({windowMs:60*60*1000,max:50,standardHeaders:true,legacyHeaders:false});
r.use(protect);
r.get('/projects/:projectId/documents',loadProject,requireProjectPermission('downloadFiles'),c.list);
r.post('/projects/:projectId/documents',requireVerifiedEmail,uploadLimiter,loadProject,requireProjectPermission('uploadFiles'),up.single('file'),c.upload);
r.get('/projects/:projectId/documents/:documentId/download',loadProject,requireProjectPermission('downloadFiles'),c.download);
r.put('/projects/:projectId/documents/:documentId/archive',loadProject,requireProjectPermission('uploadFiles'),c.archive);
r.put('/projects/:projectId/documents/:documentId/restore',loadProject,requireProjectPermission('uploadFiles'),c.restore);
r.put('/projects/:projectId/documents/:documentId/classification',loadProject,requireProjectPermission('manageMembers'),c.reclassify);
r.delete('/projects/:projectId/documents/:documentId',loadProject,requireProjectPermission('manageMembers'),c.remove);
module.exports=r;
